---
- hosts: localhost
  connection: local
  become: true

  tasks:
# ____            _                      __  __                                                   _
#|  _ \ __ _  ___| | ____ _  __ _  ___  |  \/  | __ _ _ __   __ _  __ _  ___ _ __ _    __ _ _ __ | |_
#| |_) / _` |/ __| |/ / _` |/ _` |/ _ \ | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__(_)  / _` | '_ \| __|
#|  __/ (_| | (__|   < (_| | (_| |  __/ | |  | | (_| | | | | (_| | (_| |  __/ |   _  | (_| | |_) | |_
#|_|   \__,_|\___|_|\_\__,_|\__, |\___| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|  (_)  \__,_| .__/ \__|
#                           |___/                                 |___/                    |_|
  - name: apt-get update, apt-get dist-upgrade
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist

  - name: install packages
    package:
      name:
        - vim
        - curl
        - tree #command for directory tree listing
        - htop
        - lf #range inspired file manager
        - figlet #for making text banners of ASCII characters
        - iperf3 #Internet Protocol bandwidth measuring tool
        - vifm #flexible vi-like file manager using ncurses
        - iotop #simple top-like I/O monitor
        - xboxdrv #Xbox360 gamepad driver for the userspace
      state: present

  - name: remove packages
    package:
      name:
        - nano
      state: absent
      purge: yes

  - name: remove dependencies that are no longer required
    package:
      autoremove: yes
#                          _       _
#  ___ _ __ ___  _ __     (_) ___ | |__  ___
# / __| '__/ _ \| '_ \    | |/ _ \| '_ \/ __|
#| (__| | | (_) | | | |   | | (_) | |_) \__ \
# \___|_|  \___/|_| |_|  _/ |\___/|_.__/|___/
#                       |__/
# ---- ---- ---- Add ansible cron job ---- ---- ----
  - name: add ansible user
    user:
      name: ansible_user
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible_user
      dest: /etc/sudoers.d/ansible_user
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible_user
      minute: "*/10"
      job: ansible-pull --only-if-changed -U https://github.com/JoshuaJWhite/ansible.git

#   _               _
#  | |__   __ _ ___| |__  _ __ ___
#  | '_ \ / _` / __| '_ \| '__/ __|
# _| |_) | (_| \__ \ | | | | | (__
#(_)_.__/ \__,_|___/_| |_|_|  \___|
  - name: copy bashrc file
    copy:
      src: files/bashrc
      dest: /home/htpc/.bashrc
      owner: htpc
      group: htpc
      mode: 0644 #-rw-r--r--

#       _
#__   _(_)_ __ ___  _ __ ___
#\ \ / / | '_ ` _ \| '__/ __|
# \ V /| | | | | | | | | (__
#(_)_/ |_|_| |_| |_|_|  \___|
  - name: copy vimrc config file
    ansible.builtin.copy:
      src: files/vimrc
      dest: /home/htpc/.vimrc
      owner: htpc
      group: htpc
      mode: 0600 #-rw-------

# __  __                   _ _       _     _
#|  \/  | ___   ___  _ __ | (_) __ _| |__ | |_
#| |\/| |/ _ \ / _ \| '_ \| | |/ _` | '_ \| __|
#| |  | | (_) | (_) | | | | | | (_| | | | | |_
#|_|  |_|\___/ \___/|_| |_|_|_|\__, |_| |_|\__|
#                              |___/
  - name: add moonlight qt to apt
    ansible.builtin.shell: curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian sudo -E bash
    args:
      executable: /bin/bash

  - name: install moonlight-qt
    package:
      name:
        - moonlight-qt
      state: present

#                   _   _                 _          _                                       _
# _   _ _ __   __ _| |_| |_ ___ _ __   __| | ___  __| |      _   _ _ __   __ _ _ __ __ _  __| | ___  ___
#| | | | '_ \ / _` | __| __/ _ \ '_ \ / _` |/ _ \/ _` |_____| | | | '_ \ / _` | '__/ _` |/ _` |/ _ \/ __|
#| |_| | | | | (_| | |_| ||  __/ | | | (_| |  __/ (_| |_____| |_| | |_) | (_| | | | (_| | (_| |  __/\__ \
# \__,_|_| |_|\__,_|\__|\__\___|_| |_|\__,_|\___|\__,_|      \__,_| .__/ \__, |_|  \__,_|\__,_|\___||___/
#                                                                 |_|    |___/
  - name: install unattended-upgrades
    package:
      name:
        - unattended-upgrades #automatic installation of security upgrades
      state: present

  - name: copy unattended-upgrades config file
    copy:
      src: files/50unattended-upgrades
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      owner: root
      group: root
      mode: 0644 #-rw-r--r--

  - name: add unattended-upgrades cron job #will run at midnight daily
    cron:
      name: ansible unattended-upgrades
      user: ansible_user
      minute: "0"
      hour: "0"
      job: /usr/bin/unattended-upgrade -d

# _               _
#| |__   ___  ___| |_ _ __   __ _ _ __ ___   ___
#| '_ \ / _ \/ __| __| '_ \ / _` | '_ ` _ \ / _ \
#| | | | (_) \__ \ |_| | | | (_| | | | | | |  __/
#|_| |_|\___/|___/\__|_| |_|\__,_|_| |_| |_|\___|
  - name: copy hostname file
    copy:
      src: files/hostname
      dest: /etc/hostname
      owner: root
      group: root
      mode: 0644 #-rw-r--r--

# _   _               _                          ____                     _
#| | | | __ _ _ __ __| |_      ____ _ _ __ ___  |  _ \  ___  ___ ___   __| | ___
#| |_| |/ _` | '__/ _` \ \ /\ / / _` | '__/ _ \ | | | |/ _ \/ __/ _ \ / _` |/ _ \
#|  _  | (_| | | | (_| |\ V  V / (_| | | |  __/ | |_| |  __/ (_| (_) | (_| |  __/
#|_| |_|\__,_|_|  \__,_| \_/\_/ \__,_|_|  \___| |____/ \___|\___\___/ \__,_|\___|
  - name: install packages for hardware video decode - youtube
    package:
      name:
        - libgles2-mesa
        - libgles2-mesa-dev
        - xorg-dev
      state: present

  # add gpu_mem=128 to boot config
  - name: copy raspberry pi boot config file
    copy:
      src: files/config.txt
      dest: /boot/config.txt
      owner: root
      group: root
      mode: 0777 #-rwxrwxrwx
      follow: true

# _____ _       _               _
#|  ___| | __ _| |_ _ __   __ _| | __
#| |_  | |/ _` | __| '_ \ / _` | |/ /
#|  _| | | (_| | |_| |_) | (_| |   <
#|_|   |_|\__,_|\__| .__/ \__,_|_|\_\
#                  |_|
  - name: install flatpak
    package:
      name:
        - flatpak
      state: present

  - name: add the flathub flatpak repository remote to the user installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: update all flatpak(s)
    ansible.builtin.command: flatpak update --noninteractive
    register: flatpak_update_output
    changed_when: "'app/' in flatpak_update_output.stdout"

  - name: install package(s) from flathub
    community.general.flatpak:
      name:
        - com.discordapp.Discord
      state: present

